#server:
#  port: 8080
#spring:
#  main:
#    banner-mode: off
#  zipkin:
#    enabled: false
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: {postgres}
#    password: {venyaka}
#    driverClassName: org.postgresql.Driver
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL8Dialect
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, prometheus